package Telas;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Dados.AppDao;

/**
 *
 * @author Vitor
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVerBebidas = new javax.swing.JButton();
        btnVerClientes = new javax.swing.JButton();
        btnVerPizzas1 = new javax.swing.JButton();
        btnVerFuncionarios1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuFuncionario = new javax.swing.JMenu();
        itmCadastrarFuncionario = new javax.swing.JMenuItem();
        itmAlterarFuncionario = new javax.swing.JMenuItem();
        itmExcluirFuncionario = new javax.swing.JMenuItem();
        itmListarFuncionario = new javax.swing.JMenuItem();
        mnuCliente = new javax.swing.JMenu();
        itmCadastrarCliente = new javax.swing.JMenuItem();
        itmAlterarCliente = new javax.swing.JMenuItem();
        itmExcluirCliente = new javax.swing.JMenuItem();
        itmListarCliente = new javax.swing.JMenuItem();
        mnuPizza = new javax.swing.JMenu();
        itmCadastrarPizza = new javax.swing.JMenuItem();
        itmAlterarPizza = new javax.swing.JMenuItem();
        itmExcluirPizza = new javax.swing.JMenuItem();
        itmListarPizza = new javax.swing.JMenuItem();
        mnuBebida = new javax.swing.JMenu();
        itmCadastrarBebida = new javax.swing.JMenuItem();
        itmAlterarBebida = new javax.swing.JMenuItem();
        itmExcluirBebida = new javax.swing.JMenuItem();
        itmListarBebida = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);
        getContentPane().setLayout(null);

        btnVerBebidas.setBackground(new java.awt.Color(255, 255, 255));
        btnVerBebidas.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerBebidas.setForeground(new java.awt.Color(0, 0, 0));
        btnVerBebidas.setText("BEBIDAS");
        btnVerBebidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerBebidasActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerBebidas);
        btnVerBebidas.setBounds(170, 110, 140, 60);

        btnVerClientes.setBackground(new java.awt.Color(255, 255, 255));
        btnVerClientes.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerClientes.setForeground(new java.awt.Color(0, 0, 0));
        btnVerClientes.setText("CLIENTES");
        btnVerClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerClientesActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerClientes);
        btnVerClientes.setBounds(170, 30, 140, 60);

        btnVerPizzas1.setBackground(new java.awt.Color(255, 255, 255));
        btnVerPizzas1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerPizzas1.setForeground(new java.awt.Color(0, 0, 0));
        btnVerPizzas1.setText("PIZZAS");
        btnVerPizzas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerPizzas1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerPizzas1);
        btnVerPizzas1.setBounds(20, 110, 140, 60);

        btnVerFuncionarios1.setBackground(new java.awt.Color(255, 255, 255));
        btnVerFuncionarios1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnVerFuncionarios1.setForeground(new java.awt.Color(0, 0, 0));
        btnVerFuncionarios1.setText("FUNCIONÁRIOS");
        btnVerFuncionarios1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerFuncionarios1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerFuncionarios1);
        btnVerFuncionarios1.setBounds(20, 30, 141, 60);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HORÁRIOS DE FUNCIONAMENTO:");
        jPanel1.add(jLabel1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Segunda-feira | 18:00h as 23:30h");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Terça-feira | 18:00h as 23:30h");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel3);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quarta-feira | 18:00h as 23:30h");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel4);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quinta-feira | 18:00h as 23:30h");
        jPanel1.add(jLabel5);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sexta-feira | 18:00h as 00:00h");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel6);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Sábado | 18:00h as 00:00h");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel7);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(330, 30, 250, 150);

        jPanel3.setBackground(new java.awt.Color(153, 0, 0));
        jPanel3.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("INTERLAGOS");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(80, 10, 90, 17);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gmail.png"))); // NOI18N
        jLabel9.setText("atendimento@pizzatime.com");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(40, 60, 190, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/endereço.png"))); // NOI18N
        jLabel11.setText("Avenida Interlagos, 209");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(40, 20, 170, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/telefone.png"))); // NOI18N
        jLabel13.setText("(11) 3288-8502 / 3288-3512");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(40, 40, 180, 40);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(40, 190, 250, 100);

        jPanel4.setBackground(new java.awt.Color(153, 0, 0));
        jPanel4.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("SANTO AMARO");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(80, 10, 110, 17);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/endereço.png"))); // NOI18N
        jLabel14.setText("Avenida Santo Amaro, 209");
        jPanel4.add(jLabel14);
        jLabel14.setBounds(40, 20, 170, 40);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/gmail.png"))); // NOI18N
        jLabel16.setText("atendimento@pizzatime.com");
        jPanel4.add(jLabel16);
        jLabel16.setBounds(40, 60, 190, 40);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/telefone.png"))); // NOI18N
        jLabel15.setText("(11) 5051-1229 / 5051-7615");
        jPanel4.add(jLabel15);
        jLabel15.setBounds(40, 40, 180, 40);

        getContentPane().add(jPanel4);
        jPanel4.setBounds(330, 190, 250, 100);

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel5);
        jPanel5.setBounds(620, 0, 10, 420);

        jPanel2.setBackground(new java.awt.Color(255, 51, 0));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(630, 250, 90, 170);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.add(jPanel7);

        getContentPane().add(jPanel6);
        jPanel6.setBounds(630, 120, 90, 130);

        jPanel8.setBackground(new java.awt.Color(0, 102, 0));
        getContentPane().add(jPanel8);
        jPanel8.setBounds(630, 0, 90, 120);

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(null);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("PizzaTime @ 2024 | Todos os direitos reservados");
        jPanel9.add(jLabel12);
        jLabel12.setBounds(130, 330, 340, 17);

        getContentPane().add(jPanel9);
        jPanel9.setBounds(0, 0, 620, 420);

        mnuFuncionario.setText("Funcionário");

        itmCadastrarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cadastrar.png"))); // NOI18N
        itmCadastrarFuncionario.setText("Cadastrar");
        itmCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmCadastrarFuncionario);

        itmAlterarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarFuncionario.setText("Alterar");
        itmAlterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmAlterarFuncionario);

        itmExcluirFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/excluir.png"))); // NOI18N
        itmExcluirFuncionario.setText("Excluir");
        itmExcluirFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmExcluirFuncionario);

        itmListarFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/listar.png"))); // NOI18N
        itmListarFuncionario.setText("Listar");
        itmListarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarFuncionarioActionPerformed(evt);
            }
        });
        mnuFuncionario.add(itmListarFuncionario);

        jMenuBar2.add(mnuFuncionario);

        mnuCliente.setText("Cliente");

        itmCadastrarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cadastrar.png"))); // NOI18N
        itmCadastrarCliente.setText("Cadastrar");
        itmCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(itmCadastrarCliente);

        itmAlterarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarCliente.setText("Alterar");
        itmAlterarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(itmAlterarCliente);

        itmExcluirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/excluir.png"))); // NOI18N
        itmExcluirCliente.setText("Excluir");
        itmExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(itmExcluirCliente);

        itmListarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/listar.png"))); // NOI18N
        itmListarCliente.setText("Listar");
        itmListarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarClienteActionPerformed(evt);
            }
        });
        mnuCliente.add(itmListarCliente);

        jMenuBar2.add(mnuCliente);

        mnuPizza.setText("Pizzas");

        itmCadastrarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cadastrar.png"))); // NOI18N
        itmCadastrarPizza.setText("Cadastrar");
        itmCadastrarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarPizzaActionPerformed(evt);
            }
        });
        mnuPizza.add(itmCadastrarPizza);

        itmAlterarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarPizza.setText("Alterar");
        itmAlterarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarPizzaActionPerformed(evt);
            }
        });
        mnuPizza.add(itmAlterarPizza);

        itmExcluirPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/excluir.png"))); // NOI18N
        itmExcluirPizza.setText("Excluir");
        itmExcluirPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirPizzaActionPerformed(evt);
            }
        });
        mnuPizza.add(itmExcluirPizza);

        itmListarPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/listar.png"))); // NOI18N
        itmListarPizza.setText("Listar");
        itmListarPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarPizzaActionPerformed(evt);
            }
        });
        mnuPizza.add(itmListarPizza);

        jMenuBar2.add(mnuPizza);

        mnuBebida.setText("Bebidas");

        itmCadastrarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/cadastrar.png"))); // NOI18N
        itmCadastrarBebida.setText("Cadastrar");
        itmCadastrarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmCadastrarBebidaActionPerformed(evt);
            }
        });
        mnuBebida.add(itmCadastrarBebida);

        itmAlterarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/alterar.png"))); // NOI18N
        itmAlterarBebida.setText("Alterar");
        itmAlterarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmAlterarBebidaActionPerformed(evt);
            }
        });
        mnuBebida.add(itmAlterarBebida);

        itmExcluirBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/excluir.png"))); // NOI18N
        itmExcluirBebida.setText("Excluir");
        itmExcluirBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmExcluirBebidaActionPerformed(evt);
            }
        });
        mnuBebida.add(itmExcluirBebida);

        itmListarBebida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/listar.png"))); // NOI18N
        itmListarBebida.setText("Listar");
        itmListarBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itmListarBebidaActionPerformed(evt);
            }
        });
        mnuBebida.add(itmListarBebida);

        jMenuBar2.add(mnuBebida);

        setJMenuBar(jMenuBar2);

        setSize(new java.awt.Dimension(732, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void itmCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarFuncionarioActionPerformed
        new CadastrarFuncionario().setVisible(true);
    }//GEN-LAST:event_itmCadastrarFuncionarioActionPerformed

    private void itmCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarClienteActionPerformed
        new CadastrarCliente().setVisible(true);
    }//GEN-LAST:event_itmCadastrarClienteActionPerformed

    private void itmAlterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarFuncionarioActionPerformed

        String n;
        n = JOptionPane.showInputDialog("Funcionário a alterar:");

        try {
            ResultSet funcionario = new AppDao().alterarFuncionarioMenu(n);

            if (funcionario.next()) {

                String nom, sen, cpf, car, cel;
                nom = funcionario.getString("nome_funcionario");
                sen = funcionario.getString("senha_funcionario");
                cpf = funcionario.getString("cpf_funcionario");
                car = funcionario.getString("cargo_funcionario");
                cel = funcionario.getString("celular_funcionario");
                new AlterarFuncionario(nom, sen, cpf, car, cel).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não cadastrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
    }//GEN-LAST:event_itmAlterarFuncionarioActionPerformed

    private void itmExcluirFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirFuncionarioActionPerformed

        String n;
        n = JOptionPane.showInputDialog("Funcionário a excluir:");

        try {
            int retorno = new AppDao().excluirFuncionario(n);
            
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Funcionário excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Funcionário não existente");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmExcluirFuncionarioActionPerformed

    private void itmListarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarFuncionarioActionPerformed
        new ListarFuncionario().setVisible(true);
    }//GEN-LAST:event_itmListarFuncionarioActionPerformed

    private void itmAlterarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarClienteActionPerformed
        
        String n;
        n = JOptionPane.showInputDialog("Cliente a alterar:");

        try {
            ResultSet cliente = new AppDao().alterarClienteMenu(n);

            if (cliente.next()) {

                String nom, sob, cpf, cel, cep;
                nom = cliente.getString("nome_cliente");
                sob = cliente.getString("sobrenome_cliente");
                cpf = cliente.getString("cpf_cliente");
                cel = cliente.getString("celular_cliente");
                cep = cliente.getString("cep_cliente");
                new AlterarCliente(nom, sob, cpf, cel, cep).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Cliente não cadastrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmAlterarClienteActionPerformed

    private void itmExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirClienteActionPerformed
        
        String n;
        n = JOptionPane.showInputDialog("Cliente a excluir:");

        try {
            int retorno = new AppDao().excluirCliente(n);
            
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Cliente não existente");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmExcluirClienteActionPerformed

    private void itmListarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarClienteActionPerformed
        new ListarCliente().setVisible(true);
    }//GEN-LAST:event_itmListarClienteActionPerformed

    private void itmCadastrarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarPizzaActionPerformed
        new CadastrarPizza().setVisible(true);
    }//GEN-LAST:event_itmCadastrarPizzaActionPerformed

    private void itmAlterarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarPizzaActionPerformed
        
        String n;
        n = JOptionPane.showInputDialog("Pizza a alterar:");

        try {
            ResultSet pizza = new AppDao().alterarPizzaMenu(n);

            if (pizza.next()) {

                String nom, des, pre, tip;
                nom = pizza.getString("nome_pizza");
                des = pizza.getString("desc_pizza");
                pre = pizza.getString("preco_pizza");
                tip = pizza.getString("tipo_pizza");
                new AlterarPizza(nom, des, pre, tip).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Cliente não cadastrado");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmAlterarPizzaActionPerformed

    private void itmExcluirPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirPizzaActionPerformed
        
        String n;
        n = JOptionPane.showInputDialog("Pizza a excluir:");

        try {
            int retorno = new AppDao().excluirPizza(n);
            
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Pizza excluída com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Pizza não existente");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmExcluirPizzaActionPerformed

    private void itmListarPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarPizzaActionPerformed
        new ListarPizza().setVisible(true);
    }//GEN-LAST:event_itmListarPizzaActionPerformed

    private void itmCadastrarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmCadastrarBebidaActionPerformed
        new CadastrarBebida().setVisible(true);
    }//GEN-LAST:event_itmCadastrarBebidaActionPerformed

    private void itmAlterarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmAlterarBebidaActionPerformed
        
        String n;
        n = JOptionPane.showInputDialog("Bebida a alterar:");

        try {
            ResultSet bebida = new AppDao().alterarBebidaMenu(n);

            if (bebida.next()) {

                String nom, pre, tip;
                nom = bebida.getString("nome_bebida");
                pre = bebida.getString("preco_bebida");
                tip = bebida.getString("tipo_bebida");
                new AlterarBebida(nom, pre, tip).setVisible(true);

            } else {
                JOptionPane.showMessageDialog(null, "Bebida não cadastrada");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmAlterarBebidaActionPerformed

    private void itmExcluirBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmExcluirBebidaActionPerformed
        
        String n;
        n = JOptionPane.showInputDialog("Bebida a excluir:");

        try {
            int retorno =new AppDao().excluirBebida(n);
            
            if (retorno == 1) {
                JOptionPane.showMessageDialog(null, "Bebida excluída com sucesso");
            } else {
                JOptionPane.showMessageDialog(null, "Bebida não existente");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro:" + ex.getMessage());
        }
        
    }//GEN-LAST:event_itmExcluirBebidaActionPerformed

    private void itmListarBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itmListarBebidaActionPerformed
        new ListarBebida().setVisible(true);
    }//GEN-LAST:event_itmListarBebidaActionPerformed

    private void btnVerBebidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerBebidasActionPerformed
        new ListarBebida().setVisible(true);
    }//GEN-LAST:event_btnVerBebidasActionPerformed

    private void btnVerClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerClientesActionPerformed
        new ListarCliente().setVisible(true);
    }//GEN-LAST:event_btnVerClientesActionPerformed

    private void btnVerPizzas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerPizzas1ActionPerformed
        new ListarPizza().setVisible(true);
    }//GEN-LAST:event_btnVerPizzas1ActionPerformed

    private void btnVerFuncionarios1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerFuncionarios1ActionPerformed
        new ListarFuncionario().setVisible(true);
    }//GEN-LAST:event_btnVerFuncionarios1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerBebidas;
    private javax.swing.JButton btnVerClientes;
    private javax.swing.JButton btnVerFuncionarios1;
    private javax.swing.JButton btnVerPizzas1;
    private javax.swing.JMenuItem itmAlterarBebida;
    private javax.swing.JMenuItem itmAlterarCliente;
    private javax.swing.JMenuItem itmAlterarFuncionario;
    private javax.swing.JMenuItem itmAlterarPizza;
    private javax.swing.JMenuItem itmCadastrarBebida;
    private javax.swing.JMenuItem itmCadastrarCliente;
    private javax.swing.JMenuItem itmCadastrarFuncionario;
    private javax.swing.JMenuItem itmCadastrarPizza;
    private javax.swing.JMenuItem itmExcluirBebida;
    private javax.swing.JMenuItem itmExcluirCliente;
    private javax.swing.JMenuItem itmExcluirFuncionario;
    private javax.swing.JMenuItem itmExcluirPizza;
    private javax.swing.JMenuItem itmListarBebida;
    private javax.swing.JMenuItem itmListarCliente;
    private javax.swing.JMenuItem itmListarFuncionario;
    private javax.swing.JMenuItem itmListarPizza;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JMenu mnuBebida;
    private javax.swing.JMenu mnuCliente;
    private javax.swing.JMenu mnuFuncionario;
    private javax.swing.JMenu mnuPizza;
    // End of variables declaration//GEN-END:variables
}
